insert into public.spell_templates (
  slug,
  name,
  level,
  school,
  casting_time,
  range_text,
  components,
  duration_text,
  concentration,
  ritual,
  description,
  higher_level_text,
  save_type,
  attack_type,
  source_name,
  source_page,
  is_official,
  tags
)
values
  -- Cantrips
  ('fire-bolt', 'Fire Bolt', 0, 'Evocation', '1 action', '120 feet', 'V, S', 'Instantaneous', false, false, 'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack. On a hit, the target takes 1d10 fire damage. A flammable object ignites if not worn or carried.', null, null, 'ranged_spell', 'Player''s Handbook', 'PHB p.242', true, '["damage","fire","cantrip"]'::jsonb),
  ('ray-of-frost', 'Ray of Frost', 0, 'Evocation', '1 action', '60 feet', 'V, S', 'Instantaneous', false, false, 'A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack. On a hit, it takes 1d8 cold damage, and its speed is reduced by 10 feet until the start of your next turn.', null, null, 'ranged_spell', 'Player''s Handbook', 'PHB p.271', true, '["damage","cold","control","cantrip"]'::jsonb),
  ('mage-hand', 'Mage Hand', 0, 'Conjuration', '1 action', '30 feet', 'V, S', '1 minute', false, false, 'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until dismissed, and can manipulate objects under the spell''s restrictions.', null, null, null, 'Player''s Handbook', 'PHB p.256', true, '["utility","cantrip"]'::jsonb),
  ('minor-illusion', 'Minor Illusion', 0, 'Illusion', '1 action', '30 feet', 'S, M', '1 minute', false, false, 'You create a sound or an image of an object within range that lasts for the duration. The illusion ends if you dismiss it or cast this spell again.', null, null, null, 'Player''s Handbook', 'PHB p.260', true, '["utility","illusion","cantrip"]'::jsonb),
  ('prestidigitation', 'Prestidigitation', 0, 'Transmutation', '1 action', '10 feet', 'V, S', 'Up to 1 hour', false, false, 'This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor magical effects within range.', null, null, null, 'Player''s Handbook', 'PHB p.267', true, '["utility","cantrip"]'::jsonb),
  ('guidance', 'Guidance', 0, 'Divination', '1 action', 'Touch', 'V, S', 'Concentration, up to 1 minute', true, false, 'You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice.', null, null, null, 'Player''s Handbook', 'PHB p.248', true, '["support","cantrip"]'::jsonb),
  ('sacred-flame', 'Sacred Flame', 0, 'Evocation', '1 action', '60 feet', 'V, S', 'Instantaneous', false, false, 'Flame-like radiance descends on a creature you can see within range. Target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.', null, 'dexterity', null, 'Player''s Handbook', 'PHB p.272', true, '["damage","radiant","cantrip"]'::jsonb),
  ('eldritch-blast', 'Eldritch Blast', 0, 'Evocation', '1 action', '120 feet', 'V, S', 'Instantaneous', false, false, 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack. On hit, target takes 1d10 force damage.', null, null, 'ranged_spell', 'Player''s Handbook', 'PHB p.237', true, '["damage","force","cantrip"]'::jsonb),
  ('vicious-mockery', 'Vicious Mockery', 0, 'Enchantment', '1 action', '60 feet', 'V', 'Instantaneous', false, false, 'You unleash a string of insults. Target that can hear you must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on its next attack roll before end of next turn.', null, 'wisdom', null, 'Player''s Handbook', 'PHB p.285', true, '["damage","debuff","cantrip"]'::jsonb),

  -- Level 1
  ('magic-missile', 'Magic Missile', 1, 'Evocation', '1 action', '120 feet', 'V, S', 'Instantaneous', false, false, 'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage.', 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.', null, null, 'Player''s Handbook', 'PHB p.257', true, '["damage","force"]'::jsonb),
  ('shield', 'Shield', 1, 'Abjuration', '1 reaction', 'Self', 'V, S', '1 round', false, false, 'An invisible barrier of magical force appears and protects you. Until start of your next turn, you have +5 bonus to AC, including against the triggering attack, and take no damage from magic missile.', null, null, null, 'Player''s Handbook', 'PHB p.275', true, '["defense","reaction"]'::jsonb),
  ('mage-armor', 'Mage Armor', 1, 'Abjuration', '1 action', 'Touch', 'V, S, M', '8 hours', false, false, 'You touch a willing creature who isn''t wearing armor; target''s base AC becomes 13 + its Dexterity modifier until the spell ends.', null, null, null, 'Player''s Handbook', 'PHB p.256', true, '["defense","buff"]'::jsonb),
  ('sleep', 'Sleep', 1, 'Enchantment', '1 action', '90 feet', 'V, S, M', '1 minute', false, false, 'This spell sends creatures into magical slumber. Roll 5d8; total determines hit points of creatures affected in ascending current HP order in a 20-foot-radius point within range.', 'When you cast this spell using a slot of 2nd level or higher, roll an additional 2d8 for each slot level above 1st.', null, null, 'Player''s Handbook', 'PHB p.276', true, '["control"]'::jsonb),
  ('cure-wounds', 'Cure Wounds', 1, 'Evocation', '1 action', 'Touch', 'V, S', 'Instantaneous', false, false, 'A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier.', 'When you cast this spell using a spell slot of 2nd level or higher, healing increases by 1d8 for each slot level above 1st.', null, null, 'Player''s Handbook', 'PHB p.230', true, '["healing"]'::jsonb),
  ('healing-word', 'Healing Word', 1, 'Evocation', '1 bonus action', '60 feet', 'V', 'Instantaneous', false, false, 'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.', 'When you cast this spell using a spell slot of 2nd level or higher, healing increases by 1d4 for each slot level above 1st.', null, null, 'Player''s Handbook', 'PHB p.250', true, '["healing","bonus-action"]'::jsonb),
  ('guiding-bolt', 'Guiding Bolt', 1, 'Evocation', '1 action', '120 feet', 'V, S', '1 round', false, false, 'A flash of light streaks toward a creature of your choice. Make a ranged spell attack. On hit, target takes 4d6 radiant damage; next attack roll against it before end of your next turn has advantage.', 'When you cast this spell using a slot of 2nd level or higher, damage increases by 1d6 per slot level above 1st.', null, 'ranged_spell', 'Player''s Handbook', 'PHB p.248', true, '["damage","radiant"]'::jsonb),
  ('bless', 'Bless', 1, 'Enchantment', '1 action', '30 feet', 'V, S, M', 'Concentration, up to 1 minute', true, false, 'You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or saving throw before spell ends, it can roll a d4 and add it to the roll.', 'When cast with a slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.', null, null, 'Player''s Handbook', 'PHB p.219', true, '["buff","concentration"]'::jsonb),
  ('detect-magic', 'Detect Magic', 1, 'Divination', '1 action', 'Self', 'V, S', 'Concentration, up to 10 minutes', true, true, 'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic, you can use your action to see a faint aura around visible magical creatures/objects and learn its school.', null, null, null, 'Player''s Handbook', 'PHB p.231', true, '["utility","ritual","concentration"]'::jsonb),
  ('identify', 'Identify', 1, 'Divination', '1 minute', 'Touch', 'V, S, M', 'Instantaneous', false, true, 'You choose one object touched throughout the casting. You learn whether it is magical and, if so, its properties and use requirements. Can also target a creature to learn spells affecting it.', null, null, null, 'Player''s Handbook', 'PHB p.252', true, '["utility","ritual"]'::jsonb),
  ('burning-hands', 'Burning Hands', 1, 'Evocation', '1 action', 'Self (15-foot cone)', 'V, S', 'Instantaneous', false, false, 'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots from your fingertips. Each creature in a 15-foot cone must make Dexterity saving throw; takes 3d6 fire damage on fail, half on success.', 'When cast with a slot of 2nd level or higher, damage increases by 1d6 for each slot level above 1st.', 'dexterity', null, 'Player''s Handbook', 'PHB p.220', true, '["damage","fire"]'::jsonb),
  ('chromatic-orb', 'Chromatic Orb', 1, 'Evocation', '1 action', '90 feet', 'V, S, M', 'Instantaneous', false, false, 'You hurl a 4-inch-diameter sphere of energy at a creature in range. Make a ranged spell attack. On hit, target takes 3d8 acid, cold, fire, lightning, poison, or thunder damage (your choice).', 'When cast with a spell slot of 2nd level or higher, damage increases by 1d8 for each slot level above 1st.', null, 'ranged_spell', 'Player''s Handbook', 'PHB p.221', true, '["damage","attack-roll"]'::jsonb),
  ('thunderwave', 'Thunderwave', 1, 'Evocation', '1 action', 'Self (15-foot cube)', 'V, S', 'Instantaneous', false, false, 'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube must make Constitution saving throw; takes 2d8 thunder damage and is pushed 10 feet on fail, half damage on success.', 'When cast with a slot of 2nd level or higher, damage increases by 1d8 for each slot level above 1st.', 'constitution', null, 'Player''s Handbook', 'PHB p.282', true, '["damage","thunder","control"]'::jsonb),
  ('faerie-fire', 'Faerie Fire', 1, 'Evocation', '1 action', '60 feet', 'V', 'Concentration, up to 1 minute', true, false, 'Each object in a 20-foot cube is outlined in blue, green, or violet light. Creatures in area when cast are outlined on failed Dexterity save. Attacks against affected creatures have advantage if attacker can see them.', null, 'dexterity', null, 'Player''s Handbook', 'PHB p.239', true, '["control","support","concentration"]'::jsonb),

  -- Level 2
  ('misty-step', 'Misty Step', 2, 'Conjuration', '1 bonus action', 'Self', 'V', 'Instantaneous', false, false, 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.', null, null, null, 'Player''s Handbook', 'PHB p.260', true, '["mobility","bonus-action"]'::jsonb),
  ('scorching-ray', 'Scorching Ray', 2, 'Evocation', '1 action', '120 feet', 'V, S', 'Instantaneous', false, false, 'You create three rays of fire and hurl them at targets within range. Make a ranged spell attack for each ray. On hit, target takes 2d6 fire damage.', 'When cast with a slot of 3rd level or higher, create one additional ray for each slot level above 2nd.', null, 'ranged_spell', 'Player''s Handbook', 'PHB p.273', true, '["damage","fire","attack-roll"]'::jsonb),
  ('invisibility', 'Invisibility', 2, 'Illusion', '1 action', 'Touch', 'V, S, M', 'Concentration, up to 1 hour', true, false, 'A creature you touch becomes invisible until spell ends. Anything the target wears/carries is invisible as long as on target''s person. Spell ends for target that attacks or casts a spell.', 'When cast with slot 3rd level or higher, target one additional creature per slot level above 2nd.', null, null, 'Player''s Handbook', 'PHB p.254', true, '["utility","stealth","concentration"]'::jsonb),
  ('mirror-image', 'Mirror Image', 2, 'Illusion', '1 action', 'Self', 'V, S', '1 minute', false, false, 'Three illusory duplicates of yourself appear in your space. Until spell ends, duplicates move with you and make it harder for enemies to target you, following the spell''s attack-targeting rules.', null, null, null, 'Player''s Handbook', 'PHB p.260', true, '["defense"]'::jsonb),
  ('hold-person', 'Hold Person', 2, 'Enchantment', '1 action', '60 feet', 'V, S, M', 'Concentration, up to 1 minute', true, false, 'Choose a humanoid you can see within range. Target must succeed on Wisdom saving throw or be paralyzed for duration. It may repeat save at end of each turn.', 'When cast with slot 3rd level or higher, target one additional humanoid per slot level above 2nd.', 'wisdom', null, 'Player''s Handbook', 'PHB p.251', true, '["control","concentration"]'::jsonb),
  ('spiritual-weapon', 'Spiritual Weapon', 2, 'Evocation', '1 bonus action', '60 feet', 'V, S', '1 minute', false, false, 'You create a floating spectral weapon within range. When you cast and as bonus action on later turns, make a melee spell attack against target within 5 feet of weapon; on hit target takes 1d8 + spellcasting modifier force damage.', 'When cast with slot 3rd level or higher, damage increases by 1d8 for every two slot levels above 2nd.', null, 'melee_spell', 'Player''s Handbook', 'PHB p.278', true, '["damage","force","bonus-action"]'::jsonb),
  ('lesser-restoration', 'Lesser Restoration', 2, 'Abjuration', '1 action', 'Touch', 'V, S', 'Instantaneous', false, false, 'You touch a creature and can end one disease or one condition afflicting it: blinded, deafened, paralyzed, or poisoned.', null, null, null, 'Player''s Handbook', 'PHB p.255', true, '["healing","support"]'::jsonb),
  ('web', 'Web', 2, 'Conjuration', '1 action', '60 feet', 'V, S, M', 'Concentration, up to 1 hour', true, false, 'You conjure a mass of thick, sticky webbing at a point within range. The webs are difficult terrain and can restrain creatures that fail Dexterity saving throws under the spell''s rules.', null, 'dexterity', null, 'Player''s Handbook', 'PHB p.287', true, '["control","concentration"]'::jsonb),
  ('suggestion', 'Suggestion', 2, 'Enchantment', '1 action', '30 feet', 'V, M', 'Concentration, up to 8 hours', true, false, 'You suggest a course of activity to a creature that can hear and understand you within range. Target must make Wisdom saving throw; on fail, it pursues the suggested course to the best of its ability.', null, 'wisdom', null, 'Player''s Handbook', 'PHB p.279', true, '["control","social","concentration"]'::jsonb),
  ('shatter', 'Shatter', 2, 'Evocation', '1 action', '60 feet', 'V, S, M', 'Instantaneous', false, false, 'A sudden loud ringing noise erupts from point within range. Each creature in 10-foot-radius sphere must make Constitution saving throw; takes 3d8 thunder damage on fail, half on success. Nonmagical objects also take damage.', 'When cast with slot 3rd level or higher, damage increases by 1d8 per slot level above 2nd.', 'constitution', null, 'Player''s Handbook', 'PHB p.275', true, '["damage","thunder"]'::jsonb)
on conflict (slug) do update
set
  name = excluded.name,
  level = excluded.level,
  school = excluded.school,
  casting_time = excluded.casting_time,
  range_text = excluded.range_text,
  components = excluded.components,
  duration_text = excluded.duration_text,
  concentration = excluded.concentration,
  ritual = excluded.ritual,
  description = excluded.description,
  higher_level_text = excluded.higher_level_text,
  save_type = excluded.save_type,
  attack_type = excluded.attack_type,
  source_name = excluded.source_name,
  source_page = excluded.source_page,
  is_official = excluded.is_official,
  tags = excluded.tags,
  updated_at = now();
