insert into public.item_templates (
  slug,
  name,
  category,
  rarity,
  weight,
  value_text,
  requires_attunement,
  description,
  properties,
  tags,
  item_kind,
  item_subtype,
  charges_max,
  charges_current,
  usage_type,
  source_name,
  source_code,
  source_page,
  source_url,
  is_official
)
values
  ('potion-of-healing', 'Potion of Healing', 'Consumables', 'common', 0.5, '50 gp', false, 'You regain 2d4 + 2 hit points when you drink this potion.', '["healing"]'::jsonb, '["consumable","potion","healing"]'::jsonb, 'consumable', 'potion', null, null, 'single_use', 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://www.dndbeyond.com/magic-items/4708-potion-of-healing', false),
  ('potion-of-greater-healing', 'Potion of Greater Healing', 'Consumables', 'uncommon', 0.5, '200 gp', false, 'You regain 4d4 + 4 hit points when you drink this potion.', '["healing"]'::jsonb, '["consumable","potion","healing"]'::jsonb, 'consumable', 'potion', null, null, 'single_use', 'Dungeon Master''s Guide', 'DMG', 'DMG p.187', 'https://www.dndbeyond.com/magic-items/4704-potion-of-greater-healing', false),
  ('rations-1-day', 'Rations (1 day)', 'Consumables', null, 2, '5 sp', false, 'Dry food suitable for long travel. One pack feeds one creature for one day.', '["food"]'::jsonb, '["consumable","food"]'::jsonb, 'consumable', 'ration', null, null, 'quantity', 'Player''s Handbook', 'PHB', 'PHB p.150', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('arrows-20', 'Arrows (20)', 'Consumables', null, 1, '1 gp', false, 'A bundle of twenty arrows for shortbows and longbows.', '["ammunition"]'::jsonb, '["consumable","ammo","bundle"]'::jsonb, 'consumable', 'ammunition', null, null, 'quantity', 'Player''s Handbook', 'PHB', 'PHB p.150', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('bolts-20', 'Bolts (20)', 'Consumables', null, 1.5, '1 gp', false, 'A bundle of twenty crossbow bolts.', '["ammunition"]'::jsonb, '["consumable","ammo","bundle"]'::jsonb, 'consumable', 'ammunition', null, null, 'quantity', 'Player''s Handbook', 'PHB', 'PHB p.150', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('oil-flask', 'Oil Flask', 'Consumables', null, 1, '1 sp', false, 'A flask of oil. Can fuel lanterns or be thrown and ignited.', '["fuel"]'::jsonb, '["consumable","fuel"]'::jsonb, 'consumable', 'oil', null, null, 'quantity', 'Player''s Handbook', 'PHB', 'PHB p.152', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('antitoxin', 'Antitoxin', 'Consumables', null, 0, '50 gp', false, 'For 1 hour after drinking this vial, you have advantage on saving throws against poison.', '["poison"]'::jsonb, '["consumable","antitoxin"]'::jsonb, 'consumable', 'potion', null, null, 'single_use', 'Player''s Handbook', 'PHB', 'PHB p.150', 'https://dnd5e.wikidot.com/adventuring-gear', false)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  weight = excluded.weight,
  value_text = excluded.value_text,
  requires_attunement = excluded.requires_attunement,
  description = excluded.description,
  properties = excluded.properties,
  tags = excluded.tags,
  item_kind = excluded.item_kind,
  item_subtype = excluded.item_subtype,
  charges_max = excluded.charges_max,
  charges_current = excluded.charges_current,
  usage_type = excluded.usage_type,
  source_name = excluded.source_name,
  source_code = excluded.source_code,
  source_page = excluded.source_page,
  source_url = excluded.source_url,
  is_official = excluded.is_official,
  updated_at = now();
