insert into public.item_templates (
  slug,
  name,
  category,
  rarity,
  weight,
  value_text,
  requires_attunement,
  description,
  properties,
  tags,
  item_kind,
  item_subtype,
  capacity_text,
  contents_summary,
  source_name,
  source_code,
  source_page,
  source_url,
  is_official
)
values
  ('backpack', 'Backpack', 'Equipment', null, 5, '2 gp', false, 'A sturdy leather pack with shoulder straps for carrying adventuring gear.', '["container"]'::jsonb, '["gear","container","pack"]'::jsonb, 'gear', 'backpack', '1 cubic foot / 30 lb. of gear', null, 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('bedroll', 'Bedroll', 'Equipment', null, 7, '1 gp', false, 'A simple roll of bedding for resting in the wild or on the road.', '["camping"]'::jsonb, '["gear","camp"]'::jsonb, 'gear', 'bedroll', null, null, 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('rope-hempen-50ft', 'Rope (50 ft)', 'Equipment', null, 10, '1 gp', false, 'Hempen rope suitable for climbing, tying, hauling, and securing loads.', '["utility"]'::jsonb, '["gear","rope"]'::jsonb, 'gear', 'rope', null, null, 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('torch', 'Torch', 'Equipment', null, 1, '1 cp', false, 'A wooden torch that burns for 1 hour and provides bright and dim light.', '["light"]'::jsonb, '["gear","light-source"]'::jsonb, 'gear', 'torch', null, null, 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('waterskin', 'Waterskin', 'Equipment', null, 5, '2 sp', false, 'A leather pouch used to carry water while traveling.', '["container"]'::jsonb, '["gear","container"]'::jsonb, 'gear', 'container', '4 pints of liquid', null, 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('mess-kit', 'Mess Kit', 'Equipment', null, 1, '2 sp', false, 'Includes a cup and simple cutlery for preparing and eating meals.', '["camping"]'::jsonb, '["gear","tool","camp"]'::jsonb, 'gear', 'tool', null, 'Cup, plate, utensils', 'Player''s Handbook', 'PHB', 'PHB p.152', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('crowbar', 'Crowbar', 'Equipment', null, 5, '2 gp', false, 'A heavy iron bar that grants leverage for prying open objects.', '["utility"]'::jsonb, '["gear","tool"]'::jsonb, 'gear', 'tool', null, null, 'Player''s Handbook', 'PHB', 'PHB p.151', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('hammer', 'Hammer', 'Equipment', null, 3, '1 gp', false, 'A one-handed tool used for driving spikes and basic repairs.', '["utility"]'::jsonb, '["gear","tool"]'::jsonb, 'gear', 'tool', null, null, 'Player''s Handbook', 'PHB', 'PHB p.151', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('pitons-10', 'Pitons (10)', 'Equipment', null, 2.5, '5 sp', false, 'Ten iron spikes used with a hammer to anchor rope and secure climbing routes.', '["climbing"]'::jsonb, '["gear","tool","climbing"]'::jsonb, 'gear', 'tool', null, '10 iron pitons', 'Player''s Handbook', 'PHB', 'PHB p.152', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('tinderbox', 'Tinderbox', 'Equipment', null, 1, '5 sp', false, 'Flint, fire steel, and tinder for starting open flames.', '["utility"]'::jsonb, '["gear","tool","fire"]'::jsonb, 'gear', 'tool', null, 'Flint, fire steel, tinder', 'Player''s Handbook', 'PHB', 'PHB p.153', 'https://dnd5e.wikidot.com/adventuring-gear', false),
  ('lantern-hooded', 'Lantern (Hooded)', 'Equipment', null, 2, '5 gp', false, 'A hooded lantern burns oil and can be shuttered to control light.', '["light"]'::jsonb, '["gear","light-source"]'::jsonb, 'gear', 'container', null, 'Consumes oil flasks as fuel', 'Player''s Handbook', 'PHB', 'PHB p.152', 'https://dnd5e.wikidot.com/adventuring-gear', false)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  weight = excluded.weight,
  value_text = excluded.value_text,
  requires_attunement = excluded.requires_attunement,
  description = excluded.description,
  properties = excluded.properties,
  tags = excluded.tags,
  item_kind = excluded.item_kind,
  item_subtype = excluded.item_subtype,
  capacity_text = excluded.capacity_text,
  contents_summary = excluded.contents_summary,
  source_name = excluded.source_name,
  source_code = excluded.source_code,
  source_page = excluded.source_page,
  source_url = excluded.source_url,
  is_official = excluded.is_official,
  updated_at = now();
