insert into public.item_templates (
  slug,
  name,
  category,
  rarity,
  weight,
  value_text,
  requires_attunement,
  description,
  properties,
  tags,
  damage_text,
  damage_type,
  range_text,
  weapon_kind,
  source_name,
  source_page,
  source_url,
  is_official
)
values
  ('light-hammer', 'Light Hammer', 'Weapons', null, 2, '2 gp', false, 'A small hammer balanced for close strikes and quick throws in skirmishes.', '["light","thrown"]'::jsonb, '["weapon","simple","melee","ranged"]'::jsonb, '1d4', 'bludgeoning', '20/60', 'simple_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('mace', 'Mace', 'Weapons', null, 4, '5 gp', false, 'A solid one-handed weapon with a weighted head designed to crush armored foes.', '[]'::jsonb, '["weapon","simple","melee"]'::jsonb, '1d6', 'bludgeoning', null, 'simple_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('quarterstaff', 'Quarterstaff', 'Weapons', null, 4, '2 sp', false, 'A sturdy staff useful for travelers and spellcasters, effective in close combat.', '["versatile"]'::jsonb, '["weapon","simple","melee"]'::jsonb, '1d6 (1d8 versatile)', 'bludgeoning', null, 'simple_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('sickle', 'Sickle', 'Weapons', null, 2, '1 gp', false, 'A curved blade adapted from an agricultural tool for quick close-quarters cuts.', '["light"]'::jsonb, '["weapon","simple","melee"]'::jsonb, '1d4', 'slashing', null, 'simple_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('spear', 'Spear', 'Weapons', null, 3, '1 gp', false, 'A straightforward pole weapon that can be thrust in melee or thrown at moderate range.', '["thrown","versatile"]'::jsonb, '["weapon","simple","melee","ranged"]'::jsonb, '1d6 (1d8 versatile)', 'piercing', '20/60', 'simple_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),

  ('light-crossbow', 'Light Crossbow', 'Weapons', null, 5, '25 gp', false, 'A compact crossbow favored for reliable ranged fire with manageable draw strength.', '["ammunition","loading","two-handed"]'::jsonb, '["weapon","simple","ranged"]'::jsonb, '1d8', 'piercing', '80/320', 'simple_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('dart', 'Dart', 'Weapons', null, 0.25, '5 cp', false, 'A light throwing missile suited for precise ranged attacks at short distances.', '["finesse","thrown"]'::jsonb, '["weapon","simple","ranged"]'::jsonb, '1d4', 'piercing', '20/60', 'simple_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('shortbow', 'Shortbow', 'Weapons', null, 2, '25 gp', false, 'A flexible bow that offers quick handling and dependable ranged attacks.', '["ammunition","two-handed"]'::jsonb, '["weapon","simple","ranged"]'::jsonb, '1d6', 'piercing', '80/320', 'simple_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('sling', 'Sling', 'Weapons', null, 0, '1 sp', false, 'A simple cord-and-pouch launcher that hurls stones with surprising force.', '["ammunition"]'::jsonb, '["weapon","simple","ranged"]'::jsonb, '1d4', 'bludgeoning', '30/120', 'simple_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),

  ('battleaxe', 'Battleaxe', 'Weapons', null, 4, '10 gp', false, 'A heavy chopping weapon that can be wielded in one hand or with two for stronger blows.', '["versatile"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8 (1d10 versatile)', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('flail', 'Flail', 'Weapons', null, 2, '10 gp', false, 'A spiked striking weapon on a chain, designed to batter through defenses.', '[]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8', 'bludgeoning', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('glaive', 'Glaive', 'Weapons', null, 6, '20 gp', false, 'A long polearm with a broad blade, built to keep foes at reach.', '["heavy","reach","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d10', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('greataxe', 'Greataxe', 'Weapons', null, 7, '30 gp', false, 'A massive two-handed axe that delivers brutal cleaving strikes.', '["heavy","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d12', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('greatsword', 'Greatsword', 'Weapons', null, 6, '50 gp', false, 'A large two-handed blade made for powerful sweeping attacks.', '["heavy","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '2d6', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('halberd', 'Halberd', 'Weapons', null, 6, '20 gp', false, 'A polearm combining axe blade and point, effective for controlling melee distance.', '["heavy","reach","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d10', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('lance', 'Lance', 'Weapons', null, 6, '10 gp', false, 'A long cavalry weapon meant for mounted charges and strong thrusting attacks.', '["reach","special"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d12', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('longsword', 'Longsword', 'Weapons', null, 3, '15 gp', false, 'A versatile sword that balances control in one hand with added force in two.', '["versatile"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8 (1d10 versatile)', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('maul', 'Maul', 'Weapons', null, 10, '10 gp', false, 'A heavy two-handed hammer for crushing impacts against armor and shields.', '["heavy","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '2d6', 'bludgeoning', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('morningstar', 'Morningstar', 'Weapons', null, 4, '15 gp', false, 'A spiked-headed weapon built to punch through protection with focused force.', '[]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('pike', 'Pike', 'Weapons', null, 18, '5 gp', false, 'A very long spear-like polearm used to strike enemies before they close.', '["heavy","reach","two-handed"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d10', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('rapier', 'Rapier', 'Weapons', null, 2, '25 gp', false, 'A slender dueling blade emphasizing finesse, speed, and precision thrusts.', '["finesse"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('scimitar', 'Scimitar', 'Weapons', null, 3, '25 gp', false, 'A curved sword suited to fast slashing strikes and agile fighting styles.', '["finesse","light"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d6', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('shortsword', 'Shortsword', 'Weapons', null, 2, '10 gp', false, 'A compact blade ideal for close fighting, quick attacks, and off-hand use.', '["finesse","light"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d6', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('trident', 'Trident', 'Weapons', null, 4, '5 gp', false, 'A three-pronged pole weapon that can be used to stab in melee or thrown.', '["thrown","versatile"]'::jsonb, '["weapon","martial","melee","ranged"]'::jsonb, '1d6 (1d8 versatile)', 'piercing', '20/60', 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('war-pick', 'War Pick', 'Weapons', null, 2, '5 gp', false, 'A piercing military pick designed to punch through rigid armor.', '[]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8', 'piercing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('warhammer', 'Warhammer', 'Weapons', null, 2, '15 gp', false, 'A balanced hammer for battlefield use, capable of stronger two-handed swings.', '["versatile"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d8 (1d10 versatile)', 'bludgeoning', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('whip', 'Whip', 'Weapons', null, 3, '2 gp', false, 'A flexible weapon that trades raw damage for control and extended melee reach.', '["finesse","reach"]'::jsonb, '["weapon","martial","melee"]'::jsonb, '1d4', 'slashing', null, 'martial_melee', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),

  ('blowgun', 'Blowgun', 'Weapons', null, 1, '10 gp', false, 'A quiet ranged tube weapon that fires small darts with subtle precision.', '["ammunition","loading"]'::jsonb, '["weapon","martial","ranged"]'::jsonb, '1', 'piercing', '25/100', 'martial_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('hand-crossbow', 'Hand Crossbow', 'Weapons', null, 3, '75 gp', false, 'A compact one-handed crossbow suited for close-range ranged fighting.', '["ammunition","light","loading"]'::jsonb, '["weapon","martial","ranged"]'::jsonb, '1d6', 'piercing', '30/120', 'martial_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('heavy-crossbow', 'Heavy Crossbow', 'Weapons', null, 18, '50 gp', false, 'A powerful crossbow with long range and high stopping power, but slower handling.', '["ammunition","heavy","loading","two-handed"]'::jsonb, '["weapon","martial","ranged"]'::jsonb, '1d10', 'piercing', '100/400', 'martial_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('longbow', 'Longbow', 'Weapons', null, 2, '50 gp', false, 'A tall bow with excellent range, favored by trained archers for battlefield fire.', '["ammunition","heavy","two-handed"]'::jsonb, '["weapon","martial","ranged"]'::jsonb, '1d8', 'piercing', '150/600', 'martial_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false),
  ('net', 'Net', 'Weapons', null, 3, '1 gp', false, 'A thrown entangling weapon used to restrain a target rather than deal normal harm.', '["special","thrown"]'::jsonb, '["weapon","martial","ranged"]'::jsonb, null, null, '5/15', 'martial_ranged', 'D&D 5e Wikidot', null, 'https://dnd5e.wikidot.com/weapons', false)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  weight = excluded.weight,
  value_text = excluded.value_text,
  requires_attunement = excluded.requires_attunement,
  description = excluded.description,
  properties = excluded.properties,
  tags = excluded.tags,
  damage_text = excluded.damage_text,
  damage_type = excluded.damage_type,
  range_text = excluded.range_text,
  weapon_kind = excluded.weapon_kind,
  source_name = excluded.source_name,
  source_page = excluded.source_page,
  source_url = excluded.source_url,
  is_official = excluded.is_official,
  updated_at = now();
