insert into public.item_templates (
  slug,
  name,
  category,
  rarity,
  weight,
  value_text,
  requires_attunement,
  description,
  properties,
  tags,
  damage_text,
  damage_type,
  range_text,
  weapon_kind,
  source_name,
  source_page,
  source_url,
  is_official
)
values
  (
    'club',
    'Club',
    'Weapons',
    null,
    2,
    '1 sp',
    false,
    'A short, sturdy bludgeon that is easy to use and commonly carried as a basic melee weapon.',
    '["light"]'::jsonb,
    '["weapon","simple","melee"]'::jsonb,
    '1d4',
    'bludgeoning',
    null,
    'simple_melee',
    'D&D 5e Wikidot',
    null,
    'https://dnd5e.wikidot.com/weapons',
    false
  ),
  (
    'dagger',
    'Dagger',
    'Weapons',
    null,
    1,
    '2 gp',
    false,
    'A balanced blade suitable for close combat or throwing, favored for concealability and precision.',
    '["finesse","light","thrown"]'::jsonb,
    '["weapon","simple","melee","ranged"]'::jsonb,
    '1d4',
    'piercing',
    '20/60',
    'simple_melee',
    'D&D 5e Wikidot',
    null,
    'https://dnd5e.wikidot.com/weapons',
    false
  ),
  (
    'greatclub',
    'Greatclub',
    'Weapons',
    null,
    10,
    '2 sp',
    false,
    'A heavy two-handed club that trades finesse for raw striking power.',
    '["two-handed"]'::jsonb,
    '["weapon","simple","melee"]'::jsonb,
    '1d8',
    'bludgeoning',
    null,
    'simple_melee',
    'D&D 5e Wikidot',
    null,
    'https://dnd5e.wikidot.com/weapons',
    false
  ),
  (
    'handaxe',
    'Handaxe',
    'Weapons',
    null,
    2,
    '5 gp',
    false,
    'A compact axe useful in hand-to-hand fighting and effective when hurled at nearby targets.',
    '["light","thrown"]'::jsonb,
    '["weapon","simple","melee","ranged"]'::jsonb,
    '1d6',
    'slashing',
    '20/60',
    'simple_melee',
    'D&D 5e Wikidot',
    null,
    'https://dnd5e.wikidot.com/weapons',
    false
  ),
  (
    'javelin',
    'Javelin',
    'Weapons',
    null,
    2,
    '5 sp',
    false,
    'A light spear designed to be thrown at range while still usable in close combat.',
    '["thrown"]'::jsonb,
    '["weapon","simple","melee","ranged"]'::jsonb,
    '1d6',
    'piercing',
    '30/120',
    'simple_melee',
    'D&D 5e Wikidot',
    null,
    'https://dnd5e.wikidot.com/weapons',
    false
  )
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  weight = excluded.weight,
  value_text = excluded.value_text,
  requires_attunement = excluded.requires_attunement,
  description = excluded.description,
  properties = excluded.properties,
  tags = excluded.tags,
  damage_text = excluded.damage_text,
  damage_type = excluded.damage_type,
  range_text = excluded.range_text,
  weapon_kind = excluded.weapon_kind,
  source_name = excluded.source_name,
  source_page = excluded.source_page,
  source_url = excluded.source_url,
  is_official = excluded.is_official,
  updated_at = now();
