insert into public.item_templates (
  slug,
  name,
  category,
  rarity,
  weight,
  value_text,
  requires_attunement,
  description,
  properties,
  tags,
  item_kind,
  item_subtype,
  armor_kind,
  ac_base,
  ac_bonus,
  dex_cap,
  strength_requirement,
  stealth_disadvantage,
  don_time_text,
  doff_time_text,
  source_name,
  source_code,
  source_page,
  source_url,
  is_official
)
values
  ('padded-armor', 'Padded Armor', 'Armor', null, 8, '5 gp', false, 'Quilted layers of cloth and padding provide basic protection at low cost.', '["light"]'::jsonb, '["armor","light"]'::jsonb, 'armor', 'light', 'light', 11, null, null, null, true, '1 minute', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('leather-armor', 'Leather Armor', 'Armor', null, 10, '10 gp', false, 'Hardened leather plates offer flexible protection favored by agile combatants.', '["light"]'::jsonb, '["armor","light"]'::jsonb, 'armor', 'light', 'light', 11, null, null, null, false, '1 minute', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('studded-leather-armor', 'Studded Leather Armor', 'Armor', null, 13, '45 gp', false, 'Reinforced leather with metal studs balances mobility and improved defense.', '["light"]'::jsonb, '["armor","light"]'::jsonb, 'armor', 'light', 'light', 12, null, null, null, false, '1 minute', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('hide-armor', 'Hide Armor', 'Armor', null, 12, '10 gp', false, 'Cured hides and pelts create durable armor used where metalwork is uncommon.', '["medium"]'::jsonb, '["armor","medium"]'::jsonb, 'armor', 'medium', 'medium', 12, null, 2, null, false, '5 minutes', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('chain-shirt', 'Chain Shirt', 'Armor', null, 20, '50 gp', false, 'Interlocking metal rings worn beneath outer layers provide reliable coverage.', '["medium"]'::jsonb, '["armor","medium"]'::jsonb, 'armor', 'medium', 'medium', 13, null, 2, null, false, '5 minutes', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('scale-mail', 'Scale Mail', 'Armor', null, 45, '50 gp', false, 'Leather backing with overlapping metal scales offers strong protection at the cost of quiet movement.', '["medium"]'::jsonb, '["armor","medium"]'::jsonb, 'armor', 'medium', 'medium', 14, null, 2, null, true, '5 minutes', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('breastplate', 'Breastplate', 'Armor', null, 20, '400 gp', false, 'A shaped metal chest piece protects vital areas while leaving room for mobility.', '["medium"]'::jsonb, '["armor","medium"]'::jsonb, 'armor', 'medium', 'medium', 14, null, 2, null, false, '5 minutes', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('half-plate', 'Half Plate', 'Armor', null, 40, '750 gp', false, 'Partial heavy plating over chain and leather grants excellent defense with reduced flexibility.', '["medium"]'::jsonb, '["armor","medium"]'::jsonb, 'armor', 'medium', 'medium', 15, null, 2, null, true, '5 minutes', '1 minute', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('ring-mail', 'Ring Mail', 'Armor', null, 40, '30 gp', false, 'Leather armor reinforced with sewn metal rings offers entry-level heavy protection.', '["heavy"]'::jsonb, '["armor","heavy"]'::jsonb, 'armor', 'heavy', 'heavy', 14, null, 0, null, true, '10 minutes', '5 minutes', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('chain-mail', 'Chain Mail', 'Armor', null, 55, '75 gp', false, 'A full suit of interlocking metal links provides substantial defense for trained wearers.', '["heavy"]'::jsonb, '["armor","heavy"]'::jsonb, 'armor', 'heavy', 'heavy', 16, null, 0, 13, true, '10 minutes', '5 minutes', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('splint-armor', 'Splint Armor', 'Armor', null, 60, '200 gp', false, 'Metal strips fixed to backing materials create a rigid and protective heavy armor.', '["heavy"]'::jsonb, '["armor","heavy"]'::jsonb, 'armor', 'heavy', 'heavy', 17, null, 0, 15, true, '10 minutes', '5 minutes', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('plate-armor', 'Plate Armor', 'Armor', null, 65, '1500 gp', false, 'A full set of articulated metal plates delivers the highest standard protection.', '["heavy"]'::jsonb, '["armor","heavy"]'::jsonb, 'armor', 'heavy', 'heavy', 18, null, 0, 15, true, '10 minutes', '5 minutes', 'Player''s Handbook', 'PHB', 'PHB p.145', 'https://dnd5e.wikidot.com/armor', false),
  ('shield', 'Shield', 'Armor', null, 6, '10 gp', false, 'A reinforced guard carried in one hand to improve overall defense in combat.', '["shield"]'::jsonb, '["armor","shield"]'::jsonb, 'armor', 'shield', 'shield', null, 2, null, null, false, '1 action', '1 action', 'Player''s Handbook', 'PHB', 'PHB p.146', 'https://dnd5e.wikidot.com/armor', false)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  rarity = excluded.rarity,
  weight = excluded.weight,
  value_text = excluded.value_text,
  requires_attunement = excluded.requires_attunement,
  description = excluded.description,
  properties = excluded.properties,
  tags = excluded.tags,
  item_kind = excluded.item_kind,
  item_subtype = excluded.item_subtype,
  armor_kind = excluded.armor_kind,
  ac_base = excluded.ac_base,
  ac_bonus = excluded.ac_bonus,
  dex_cap = excluded.dex_cap,
  strength_requirement = excluded.strength_requirement,
  stealth_disadvantage = excluded.stealth_disadvantage,
  don_time_text = excluded.don_time_text,
  doff_time_text = excluded.doff_time_text,
  source_name = excluded.source_name,
  source_code = excluded.source_code,
  source_page = excluded.source_page,
  source_url = excluded.source_url,
  is_official = excluded.is_official,
  updated_at = now();
