insert into public.creature_templates (
  slug,
  name,
  size,
  creature_type,
  subtype,
  alignment,
  armor_class,
  hit_points,
  speed_text,
  str_score,
  dex_score,
  con_score,
  int_score,
  wis_score,
  cha_score,
  skills,
  senses,
  languages,
  challenge_rating,
  traits,
  actions,
  notes,
  tags,
  source_name,
  source_page,
  is_official
)
values
  ('goblin', 'Goblin', 'Small', 'Humanoid', 'goblinoid', 'neutral evil', 15, 7, '30 ft.', 8, 14, 10, 10, 8, 8, '{"Stealth":6}'::jsonb, 'Darkvision 60 ft., passive Perception 9', 'Common, Goblin', 0.25, '[{"name":"Nimble Escape","text":"Goblin can take Disengage or Hide as a bonus action on each of its turns."}]'::jsonb, '[{"name":"Scimitar","text":"Melee Weapon Attack: +4 to hit, 5 (1d6 + 2) slashing."},{"name":"Shortbow","text":"Ranged Weapon Attack: +4 to hit, range 80/320 ft., 5 (1d6 + 2) piercing."}]'::jsonb, 'Core low-CR ambusher used for early encounters and progression.', '["low-cr","humanoid","starter"]'::jsonb, 'Monster Manual', 'MM p.166', true),
  ('orc', 'Orc', 'Medium', 'Humanoid', 'orc', 'chaotic evil', 13, 15, '30 ft.', 16, 12, 16, 7, 11, 10, '{"Intimidation":2}'::jsonb, 'Darkvision 60 ft., passive Perception 10', 'Common, Orc', 0.5, '[{"name":"Aggressive","text":"As a bonus action, the orc can move up to its speed toward a hostile creature it can see."}]'::jsonb, '[{"name":"Greataxe","text":"Melee Weapon Attack: +5 to hit, 9 (1d12 + 3) slashing."},{"name":"Javelin","text":"Melee or Ranged Weapon Attack: +5 to hit, range 30/120 ft., 6 (1d6 + 3) piercing."}]'::jsonb, 'Straightforward bruiser for melee-focused encounters.', '["low-cr","humanoid"]'::jsonb, 'Monster Manual', 'MM p.246', true),
  ('skeleton', 'Skeleton', 'Medium', 'Undead', null, 'lawful evil', 13, 13, '30 ft.', 10, 14, 15, 6, 8, 5, '{}'::jsonb, 'Darkvision 60 ft., passive Perception 9', 'Understands languages it knew in life but cannot speak', 0.25, '[{"name":"Damage Vulnerability","text":"Bludgeoning."}]'::jsonb, '[{"name":"Shortsword","text":"Melee Weapon Attack: +4 to hit, 5 (1d6 + 2) piercing."},{"name":"Shortbow","text":"Ranged Weapon Attack: +4 to hit, range 80/320 ft., 5 (1d6 + 2) piercing."}]'::jsonb, 'Classic undead minion for crypt and necromancer encounters.', '["undead","low-cr"]'::jsonb, 'Monster Manual', 'MM p.272', true),
  ('zombie', 'Zombie', 'Medium', 'Undead', null, 'neutral evil', 8, 22, '20 ft.', 13, 6, 16, 3, 6, 5, '{}'::jsonb, 'Darkvision 60 ft., passive Perception 8', 'Understands languages it knew in life but cannot speak', 0.25, '[{"name":"Undead Fortitude","text":"If damage reduces zombie to 0 hp, it makes CON save (DC 5 + damage taken) unless radiant or critical; on success drops to 1 hp instead."}]'::jsonb, '[{"name":"Slam","text":"Melee Weapon Attack: +3 to hit, 4 (1d6 + 1) bludgeoning."}]'::jsonb, 'Slow but durable undead that pressures action economy.', '["undead","low-cr"]'::jsonb, 'Monster Manual', 'MM p.316', true),
  ('wolf', 'Wolf', 'Medium', 'Beast', null, 'unaligned', 13, 11, '40 ft.', 12, 15, 12, 3, 12, 6, '{"Perception":3,"Stealth":4}'::jsonb, 'Passive Perception 13', null, 0.25, '[{"name":"Keen Hearing and Smell","text":"Wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."},{"name":"Pack Tactics","text":"Wolf has advantage on an attack roll against a creature if at least one ally is within 5 feet of target and not incapacitated."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +4 to hit, 7 (2d4 + 2) piercing; target must succeed on DC 11 Strength save or be knocked prone."}]'::jsonb, 'Common wilderness threat and companion baseline creature.', '["beast","pack","low-cr"]'::jsonb, 'Monster Manual', 'MM p.341', true),
  ('giant-rat', 'Giant Rat', 'Small', 'Beast', null, 'unaligned', 12, 7, '30 ft.', 7, 15, 11, 2, 10, 4, '{"Perception":3,"Stealth":4}'::jsonb, 'Darkvision 60 ft., passive Perception 13', null, 0.125, '[{"name":"Keen Smell","text":"Giant rat has advantage on Wisdom (Perception) checks that rely on smell."},{"name":"Pack Tactics","text":"Has advantage on attack rolls if an ally is within 5 feet of target."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +4 to hit, 4 (1d4 + 2) piercing."}]'::jsonb, 'Swarm-adjacent dungeon threat for low-level parties.', '["beast","low-cr","dungeon"]'::jsonb, 'Monster Manual', 'MM p.327', true),
  ('giant-spider', 'Giant Spider', 'Large', 'Beast', null, 'unaligned', 14, 26, '30 ft., climb 30 ft.', 14, 16, 12, 2, 11, 4, '{"Stealth":7}'::jsonb, 'Blindsight 10 ft., Darkvision 60 ft., passive Perception 10', null, 1, '[{"name":"Spider Climb","text":"Can climb difficult surfaces, including upside down on ceilings, without ability check."},{"name":"Web Sense","text":"Knows location of other creature in contact with same web."},{"name":"Web Walker","text":"Ignores movement restrictions caused by webbing."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +5 to hit, 7 (1d8 + 3) piercing plus 7 (2d6) poison; DC 11 CON save for half poison."},{"name":"Web","text":"Ranged Weapon Attack: +5 to hit, range 30/60 ft.; target restrained on hit, DC 12 STR check to break."}]'::jsonb, 'Iconic hazard monster combining restraint and poison pressure.', '["beast","control","poison"]'::jsonb, 'Monster Manual', 'MM p.328', true),
  ('bandit', 'Bandit', 'Medium', 'Humanoid', 'any race', 'any non-lawful alignment', 12, 11, '30 ft.', 11, 12, 12, 10, 10, 10, '{}'::jsonb, 'Passive Perception 10', 'Any one language', 0.125, '[]'::jsonb, '[{"name":"Scimitar","text":"Melee Weapon Attack: +3 to hit, 4 (1d6 + 1) slashing."},{"name":"Light Crossbow","text":"Ranged Weapon Attack: +3 to hit, range 80/320 ft., 5 (1d8 + 1) piercing."}]'::jsonb, 'Basic humanoid opposition useful for social and combat scenarios.', '["humanoid","low-cr"]'::jsonb, 'Monster Manual', 'MM p.343', true),
  ('guard', 'Guard', 'Medium', 'Humanoid', 'any race', 'any alignment', 16, 11, '30 ft.', 13, 12, 12, 10, 11, 10, '{"Perception":2}'::jsonb, 'Passive Perception 12', 'Any one language', 0.125, '[]'::jsonb, '[{"name":"Spear","text":"Melee or Ranged Weapon Attack: +3 to hit, range 20/60 ft., 4 (1d6 + 1) piercing."}]'::jsonb, 'Defensive city/NPC statline for lawful opposition.', '["humanoid","npc","low-cr"]'::jsonb, 'Monster Manual', 'MM p.347', true),
  ('kobold', 'Kobold', 'Small', 'Humanoid', 'kobold', 'lawful evil', 12, 5, '30 ft.', 7, 15, 9, 8, 7, 8, '{}'::jsonb, 'Darkvision 60 ft., passive Perception 8', 'Common, Draconic', 0.125, '[{"name":"Sunlight Sensitivity","text":"Disadvantage on attack rolls and Wisdom (Perception) checks that rely on sight while in sunlight."},{"name":"Pack Tactics","text":"Advantage on attack roll against creature if ally is within 5 feet and not incapacitated."}]'::jsonb, '[{"name":"Dagger","text":"Melee or Ranged Weapon Attack: +4 to hit, range 20/60 ft., 4 (1d4 + 2) piercing."},{"name":"Sling","text":"Ranged Weapon Attack: +4 to hit, range 30/120 ft., 4 (1d4 + 2) bludgeoning."}]'::jsonb, 'Trap-friendly low-CR humanoid for lair-style fights.', '["humanoid","low-cr","pack"]'::jsonb, 'Monster Manual', 'MM p.195', true),
  ('bugbear', 'Bugbear', 'Medium', 'Humanoid', 'goblinoid', 'chaotic evil', 16, 27, '30 ft.', 15, 14, 13, 8, 11, 9, '{"Stealth":6,"Survival":2}'::jsonb, 'Darkvision 60 ft., passive Perception 10', 'Common, Goblin', 1, '[{"name":"Brute","text":"Melee weapon attacks deal one extra die of damage."},{"name":"Surprise Attack","text":"If bugbear surprises target and hits it on first round, attack deals extra 7 (2d6) damage."}]'::jsonb, '[{"name":"Morningstar","text":"Melee Weapon Attack: +4 to hit, 11 (2d8 + 2) piercing."},{"name":"Javelin","text":"Melee or Ranged Weapon Attack: +4 to hit, range 30/120 ft., 9 (2d6 + 2) piercing."}]'::jsonb, 'Early boss-style goblinoid with burst damage.', '["humanoid","mid-low-cr","ambush"]'::jsonb, 'Monster Manual', 'MM p.33', true),
  ('ogre', 'Ogre', 'Large', 'Giant', null, 'chaotic evil', 11, 59, '40 ft.', 19, 8, 16, 5, 7, 7, '{}'::jsonb, 'Darkvision 60 ft., passive Perception 8', 'Common, Giant', 2, '[]'::jsonb, '[{"name":"Greatclub","text":"Melee Weapon Attack: +6 to hit, 13 (2d8 + 4) bludgeoning."},{"name":"Javelin","text":"Ranged Weapon Attack: +6 to hit, range 30/120 ft., 11 (2d6 + 4) piercing."}]'::jsonb, 'Classic brute for tier-1 climax encounters.', '["giant","brute","cr2"]'::jsonb, 'Monster Manual', 'MM p.237', true),
  ('cultist', 'Cultist', 'Medium', 'Humanoid', 'any race', 'any non-good alignment', 12, 9, '30 ft.', 11, 12, 10, 10, 11, 10, '{"Deception":2,"Religion":2}'::jsonb, 'Passive Perception 10', 'Any one language', 0.125, '[{"name":"Dark Devotion","text":"Cultist has advantage on saving throws against being charmed or frightened."}]'::jsonb, '[{"name":"Scimitar","text":"Melee Weapon Attack: +3 to hit, 4 (1d6 + 1) slashing."}]'::jsonb, 'Low-tier zealot NPC for temple and conspiracy plots.', '["humanoid","npc","low-cr"]'::jsonb, 'Monster Manual', 'MM p.345', true),
  ('bandit-captain', 'Bandit Captain', 'Medium', 'Humanoid', 'any race', 'any non-lawful alignment', 15, 65, '30 ft.', 15, 16, 14, 14, 11, 14, '{"Athletics":4,"Deception":4}'::jsonb, 'Passive Perception 10', 'Any two languages', 2, '[{"name":"Multiattack","text":"Bandit captain makes three melee attacks: two with scimitar and one with dagger."}]'::jsonb, '[{"name":"Scimitar","text":"Melee Weapon Attack: +5 to hit, 6 (1d6 + 3) slashing."},{"name":"Dagger","text":"Melee or Ranged Weapon Attack: +5 to hit, range 20/60 ft., 5 (1d4 + 3) piercing."}]'::jsonb, 'Humanoid lieutenant for social/combat campaign arcs.', '["humanoid","leader","cr2"]'::jsonb, 'Monster Manual', 'MM p.344', true),
  ('ghoul', 'Ghoul', 'Medium', 'Undead', null, 'chaotic evil', 12, 22, '30 ft.', 13, 15, 10, 7, 10, 6, '{}'::jsonb, 'Darkvision 60 ft., passive Perception 10', 'Common', 1, '[{"name":"Turn Defiance","text":"Ghoul has advantage on saving throws against effects that turn undead."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +2 to hit, 9 (2d6 + 2) piercing."},{"name":"Claws","text":"Melee Weapon Attack: +4 to hit, 7 (2d4 + 2) slashing; target must succeed on DC 10 CON save or be paralyzed (except undead)."}]'::jsonb, 'Undead controller threat through paralysis effect.', '["undead","control","cr1"]'::jsonb, 'Monster Manual', 'MM p.148', true),
  ('dire-wolf', 'Dire Wolf', 'Large', 'Beast', null, 'unaligned', 14, 37, '50 ft.', 17, 15, 15, 3, 12, 7, '{"Perception":3,"Stealth":4}'::jsonb, 'Passive Perception 13', null, 1, '[{"name":"Keen Hearing and Smell","text":"Advantage on Wisdom (Perception) checks that rely on hearing or smell."},{"name":"Pack Tactics","text":"Advantage on attack roll if ally within 5 feet of target."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +5 to hit, 10 (2d6 + 3) piercing; DC 13 STR save or target knocked prone."}]'::jsonb, 'Advanced pack predator for wilderness escalation.', '["beast","pack","cr1"]'::jsonb, 'Monster Manual', 'MM p.321', true),
  ('brown-bear', 'Bear', 'Large', 'Beast', null, 'unaligned', 11, 34, '40 ft., climb 30 ft.', 19, 10, 16, 2, 13, 7, '{"Perception":3}'::jsonb, 'Passive Perception 13', null, 1, '[{"name":"Keen Smell","text":"Advantage on Wisdom (Perception) checks that rely on smell."}]'::jsonb, '[{"name":"Multiattack","text":"Bear makes two attacks: one with bite and one with claws."},{"name":"Bite","text":"Melee Weapon Attack: +5 to hit, 8 (1d8 + 4) piercing."},{"name":"Claws","text":"Melee Weapon Attack: +5 to hit, 11 (2d6 + 4) slashing."}]'::jsonb, 'Solid CR1 beast for druid forms and wilderness fights.', '["beast","cr1"]'::jsonb, 'Monster Manual', 'MM p.319', true),
  ('spider', 'Spider', 'Tiny', 'Beast', null, 'unaligned', 12, 1, '20 ft., climb 20 ft.', 2, 14, 8, 1, 10, 2, '{"Stealth":4}'::jsonb, 'Darkvision 30 ft., passive Perception 10', null, 0, '[{"name":"Spider Climb","text":"Can climb difficult surfaces, including upside down on ceilings, without ability check."},{"name":"Web Sense","text":"Knows location of creatures in contact with same web."},{"name":"Web Walker","text":"Ignores movement restrictions caused by webbing."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +4 to hit, 1 piercing plus 2 (1d4) poison; DC 9 CON save for half poison."}]'::jsonb, 'Tiny hazard/scout creature and common familiar choice.', '["beast","tiny","scout"]'::jsonb, 'Monster Manual', 'MM p.337', true),
  ('imp', 'Imp', 'Tiny', 'Fiend', 'devil', 'lawful evil', 13, 10, '20 ft., fly 40 ft.', 6, 17, 13, 11, 12, 14, '{"Deception":4,"Insight":3,"Persuasion":4,"Stealth":5}'::jsonb, 'Darkvision 120 ft., passive Perception 11', 'Infernal, Common', 1, '[{"name":"Shapechanger","text":"Imp can polymorph into beast forms or back to true form."},{"name":"Devil''s Sight","text":"Magical darkness does not impede imp''s darkvision."},{"name":"Magic Resistance","text":"Advantage on saving throws against spells and magical effects."}]'::jsonb, '[{"name":"Sting","text":"Melee Weapon Attack: +5 to hit, 5 (1d4 + 3) piercing plus 10 (3d6) poison; DC 11 CON save halves poison."},{"name":"Invisibility","text":"Imp magically turns invisible until it attacks or concentration ends."}]'::jsonb, 'Fiend familiar and infiltration specialist for infernal themes.', '["fiend","familiar","cr1"]'::jsonb, 'Monster Manual', 'MM p.76', true),
  ('pseudodragon', 'Pseudodragon', 'Tiny', 'Dragon', null, 'neutral good', 13, 7, '15 ft., fly 60 ft.', 6, 15, 13, 10, 12, 10, '{"Perception":3,"Stealth":4}'::jsonb, 'Blindsight 10 ft., Darkvision 60 ft., passive Perception 13', 'Understands Common and Draconic', 0.25, '[{"name":"Keen Senses","text":"Advantage on Wisdom (Perception) checks relying on sight, hearing, or smell."},{"name":"Magic Resistance","text":"Advantage on saving throws against spells and magical effects."},{"name":"Limited Telepathy","text":"Can communicate simple ideas telepathically with creatures within 100 feet that understand a language."}]'::jsonb, '[{"name":"Bite","text":"Melee Weapon Attack: +4 to hit, 5 (1d4 + 3) piercing."},{"name":"Sting","text":"Melee Weapon Attack: +4 to hit, 5 (1d4 + 3) piercing; target DC 11 CON save vs poison and possible unconsciousness."}]'::jsonb, 'Dragon familiar-style ally with utility and status effects.', '["dragon","familiar","low-cr"]'::jsonb, 'Monster Manual', 'MM p.254', true)
on conflict (slug) do update
set
  name = excluded.name,
  size = excluded.size,
  creature_type = excluded.creature_type,
  subtype = excluded.subtype,
  alignment = excluded.alignment,
  armor_class = excluded.armor_class,
  hit_points = excluded.hit_points,
  speed_text = excluded.speed_text,
  str_score = excluded.str_score,
  dex_score = excluded.dex_score,
  con_score = excluded.con_score,
  int_score = excluded.int_score,
  wis_score = excluded.wis_score,
  cha_score = excluded.cha_score,
  skills = excluded.skills,
  senses = excluded.senses,
  languages = excluded.languages,
  challenge_rating = excluded.challenge_rating,
  traits = excluded.traits,
  actions = excluded.actions,
  notes = excluded.notes,
  tags = excluded.tags,
  source_name = excluded.source_name,
  source_page = excluded.source_page,
  is_official = excluded.is_official,
  updated_at = now();
